model_name: openai/clip-vit-base-patch32
use_lora: true
use_mrl: true
data_path: data/train.jsonl
val_data_path: data/val.jsonl
image_root: data/images
output_dir: experiments/output_distill
epochs: 5
batch_size: 64
learning_rate: 5.0e-05
teacher_model_name: openai/clip-vit-large-patch14
distillation_alpha: 0.5
distillation_temperature: 2.0
distillation_loss_type: kl
num_gpus: 2
