model_name: facebook/dinov2-base
retrieval_mode: i2i
use_lora: true
data_path: data/stanford_online_products/train.jsonl
val_data_path: data/stanford_online_products/val.jsonl
image_root: data/stanford_online_products
output_dir: experiments/output_sop_dinov2_i2i
epochs: 20
batch_size: 128
learning_rate: 0.0001
loss_type: infonce
report_to: none
logging_steps: 10
save_steps: 1000
