model_name: facebook/dinov2-base
retrieval_mode: i2i
use_lora: true
topk_tokens: 32
projection_dim: 128
pooling_strategy: none
data_path: data/stanford_online_products/train.jsonl
val_data_path: data/stanford_online_products/val.jsonl
image_root: data/stanford_online_products
output_dir: experiments/output_sop_dinov2_colbert
epochs: 20
batch_size: 128
learning_rate: 5.0e-05
loss_type: colbert
use_gradient_cache: true
report_to: none
logging_steps: 10
save_steps: 1000
