# MAE Image-to-Image Training Configuration
# Trained on Stanford Online Products (SOP)

# --- Model ---
model_type: "custom"
model_name: "facebook/vit-mae-base"
pooling_method: "mean"
retrieval_mode: "i2i"
use_lora: false

# --- Data ---
data_path: "data/stanford_online_products/train.jsonl"
val_data_path: "data/stanford_online_products/val.jsonl"
image_root: "data/stanford_online_products"

# --- Training ---
output_dir: "experiments/output_sop_mae_i2i"
epochs: 50
batch_size: 128
learning_rate: 1.0e-4
loss_type: "infonce"

# --- Logging ---
report_to: "none"
logging_steps: 10
save_steps: 1000
