model_name: Qwen/Qwen2-7B-Instruct
retrieval_mode: m2t
use_lora: true
data_path: data/train.jsonl
val_data_path: data/val.jsonl
image_root: data/images
output_dir: experiments/output_qwen_m2t
epochs: 3
batch_size: 128
use_gradient_cache: true
gradient_cache_chunk_size: 4
