# SigLIP Training Configuration

# --- Model ---
model_type: "siglip"  # Base preset
use_lora: true

# --- Data ---
data_path: "data/train.jsonl"
val_data_path: "data/val.jsonl"
image_root: "data/images"

# --- Training ---
output_dir: "experiments/output_siglip"
epochs: 10
batch_size: 256
learning_rate: 2.0e-4
loss_type: "sigmoid"
