model_name: google/siglip-so400m-14-flash
use_lora: true
data_path: data/train.jsonl
val_data_path: data/val.jsonl
image_root: data/images
output_dir: experiments/output_siglip
epochs: 10
batch_size: 256
learning_rate: 0.0002
loss_type: sigmoid
